model_endpoint_dict = {
    # 0 - General
    "qwen": {
        "url": "http://localhost:8000/v1/completions",
        "model_id": "Qwen/Qwen2.5-7B-Instruct",
        "domain": "general",
        "model_card": '- **Domain**: General-purpose\n- **Task Specialization**: \n  - Instruction following\n  - Text generation\n  - Long text generation (over 8K tokens)\n  - Understanding and generating structured data (e.g., tables, JSON)\n  - Code generation and mathematics\n  - Multilingual support (over 29 languages, including Chinese, English, French, Spanish, Portuguese, German, Italian, Russian, Japanese, Korean, Vietnamese, Thai, Arabic, etc.)\n- **Parameter Size**: 7.61B\n- **Special Features**: \n  - Fine-tuned for instruction-following tasks\n  - Enhanced capabilities in coding and mathematics\n  - Long-context support up to 128K tokens\n  - Support for generating up to 8K tokens\n  - Multilingual support across 29 languages\n  - Utilizes YaRN for handling long texts beyond the default context length'
    },

    # 1 - Code
    "qwen_coder": {
        "url": "http://localhost:8001/v1/completions",
        "model_id": "Qwen/Qwen2.5-Coder-7B-Instruct",
        "domain": "code",
        "model_card": '- **Domain**: Coding\n- **Task Specialization**: \n  - Code generation\n  - Code reasoning\n  - Code fixing\n- **Parameter Size**: 7.61B\n- **Special Features**: \n  - Instruction-tuned\n  - Fine-tuned on 5.5 trillion training tokens including source code, text-code grounding, Synthetic data, etc.\n  - Supports long-context up to 128K tokens\n  - Enhanced coding capabilities with performance comparable to GPT-4o\n  - Comprehensive foundation for real-world applications such as Code Agents'
    },

    # 2 - Math
    "mathstral": {
        "url": "http://localhost:8002/v1/completions",
        "model_id": "mistralai/Mathstral-7B-v0.1",
        "domain": "math",
        "model_card": '- **Domain**: Math and Science\n- **Task Specialization**: \n  - Mathematical problem solving\n  - Scientific inquiry\n- **Parameter Size**: 7B (7 billion)\n- **Special Features**: \n  - Based on the Mistral 7B architecture\n  - Designed for mathematical and scientific tasks\n  - Includes a chat interface for interactive problem solving'
    },

    # 3 - Biomedical
    "biomedical_llama": {
        "url": "http://localhost:8003/v1/completions",
        "model_id": "ContactDoctor/Bio-Medical-Llama-3-8B",
        "domain": "biomedical",
        "model_card": '- **Domain**: Biomedical\n- **Task Specialization**: \n  - Biomedical question answering\n  - Clinical decision support\n  - Educational resource for biomedical knowledge expansion\n- **Parameter Size**: 8 billion\n- **Special Features**: \n  - Fine-tuned from the meta-llama/Meta-Llama-3-8B-Instruct model\n  - Trained on a custom "BioMedData" dataset containing over 500,000 diverse entries, including both synthetic and manually curated data\n  - Designed to understand and generate text related to various biomedical fields'
    },

    # 4 - Finance
    "finance_llama": {
        "url": "http://localhost:8004/v1/completions",
        "model_id": "instruction-pretrain/finance-Llama3-8B",
        "domain": "finance",
        "model_card": '- **Domain**: Finance\n- **Task Specialization**: \n  - Financial sentiment classification\n  - Financial fact-based question answering\n- **Parameter Size**: 8 billion parameters\n- **Special Features**: \n  - Pre-trained using the Instruction Pre-Training framework, which augments raw corpora with instruction-response pairs generated by an efficient instruction synthesizer\n  - Designed for domain-specific tasks, particularly in the finance domain\n  - Fine-tuned on domain-specific corpora with instruction-response pairs to enhance performance in finance-related tasks'
    },

    # 5 - Legal
    "saul": {
        "url": "http://localhost:8005/v1/completions",
        "model_id": "Equall/Saul-7B-Instruct-v1",
        "domain": "legal",
        "model_card": '- **Domain**: Legal\n- **Task Specialization**: Legal use cases involving generation, such as generating legal documents or providing legal advice.\n- **Parameter Size**: 7B\n- **Special Features**: Built upon the Mistral-7B model and tailored for the legal domain.'
    }
}